### ISSUE TITLE
Which defconfig to use for mi A2?

### ISSUE THREAD

**Issue by beakthoven** [tytydraco/hex_jasmine#6]
Hello devs,

I am a rookie in kernel development, can I know which defconfig file to use for mi A2

Thank you

**Comment by tytydraco** [comment]
Should be hex_defconfig.

**Comment by beakthoven** [comment]
ok thank you very much, can i know how can i contact you as i want to develop a custom kernel for gamers which has cpu/gpu overclocks and better customized governors for better performance! so i need help in developing it thats the reason i want to contact you.

**Comment by tytydraco** [comment]
Contact me @tytydraco on Telegram 👍
